[build]
  command = "npm install && mkdir -p dist && cp index.html dist/ && cp -f favicon.* *.png site.webmanifest dist/ 2>/dev/null || true"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  SECRETS_SCAN_ENABLED = "false"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"

# Scheduled function for daily reports
[functions."daily-report"]
  schedule = "0 9 * * *"  # Daily at 9 AM UTC

# Headers for OG image
[[headers]]
  for = "/og-image.png"
  [headers.values]
    Cache-Control = "public, max-age=604800, immutable"
    Content-Type = "image/png"
    X-Content-Type-Options = "nosniff"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=604800"
    X-Content-Type-Options = "nosniff"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://js.stripe.com https://api.telegram.org; script-src 'self' 'unsafe-inline' https://js.stripe.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://api.stripe.com https://*.netlify.app"